<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="OperationTests.fs" />
    <Compile Include="SolutionTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" Version="10.1.0" />
    <PackageReference Include="FsCheck.Xunit.v3" Version="3.4.0" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\countle.fsproj" />
  </ItemGroup>
</Project>
